### ISSUE TITLE
Broken links to SDKs

### ISSUE THREAD

**Issue by cullywakelin** [temporalio/temporal-documentation-legacy-v2#22]
At the bottom of this page: https://docs.temporal.io/docs/installing-server there are two links that are broken. One is supposed to link to the Java SDK, one to the Go SDK.
![image](https://user-images.githubusercontent.com/34380806/84336443-79f62b00-ab54-11ea-9da5-d4884c60623c.png)

Looks like they are meant to direct users to here: https://docs.temporal.io/docs/java-quick-start/ and here: https://docs.temporal.io/docs/go-quick-start/

But instead direct users to here: https://docs.temporal.io/java-quick-start/ and here https://docs.temporal.io/go-quick-start/

**Comment by feedmeapples** [comment]
Thank you for reporting!
